# Generated by Django 5.1 on 2024-08-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerce',
            name='user_name',
        ),
    ]
