# Generated by Django 5.1 on 2024-08-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0003_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
