# Generated by Django 5.1 on 2024-08-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0004_delete_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commerce',
        ),
    ]
