# Generated by Django 5.1 on 2024-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DjangoEcommerce', '0005_delete_commerce'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_img', models.ImageField(height_field=100, upload_to='', width_field=50)),
                ('product_describtion', models.TextField(blank=True)),
            ],
        ),
    ]
