# Generated by Django 5.1 on 2024-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='product_describtion',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='product_img',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
