# Generated by Django 5.1 on 2024-08-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0007_remove_addproduct_product_describtion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_describtion',
            field=models.TextField(null=True),
        ),
    ]
