# Generated by Django 5.1 on 2024-08-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerce', '0009_product_delete_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='DjangoEcommerce/media/images/'),
        ),
    ]
